[build-system]
requires = ["hatchling","numpy","pandas"]
build-backend = "hatchling.build"

[project]
name = "Topsis-102003706"
version = "0.0.1"
authors = [
  { name="Aditya Aggarwal", email="aditya.agg7@gmail.com" },
]
description = "Topsis packaged for ease."
readme = "README.md"
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/adityaagg7/Topsis-Package"
"Bug Tracker" = "https://github.com/adityaagg7/Topsis-Package/issues"